### ISSUE TITLE
 Collision Lab master checklist

### ISSUE THREAD

**Issue by veillette** [phetsims/collision-lab#1]
# Collision Lab master checklist

## Design
- [ ] **Sim folder and design doc created** (Date: //)
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //)
- [ ] **Mockups complete** (Date: //)
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion**
- [ ] **Interviews complete** (Date: //)
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //)
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items**
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items**
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Add to Edmodo
  - [ ] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [ ] Collaborators added (Developer team, QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to perennial/data/active-repos
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //)
- [ ] **Code review completed** (Date: //)
- [ ] **Pre-publication items**
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
- [ ] **Published** (Date: //)
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Dev testing started** (Date: //)
- [ ] **Dev testing completed** (Date: //)
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
