### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/collision-lab#156]
For #1 

I'll edit this list as I think of more items to include in the Teacher Tips.

- [x] Stick vs. Slip, #87, #65
- [x] If an object is partially out-of-bounds when the Reflecting Border is turned on, it will continue to escape.
- [x] Off-screen balls are weird sometimes - #199 
- [x] Stroke weight represents elasticity, #38
- [x] Constant size, including odd behavior if changed after perfectly inelastic collision
- [x] Precision, #162,  #182
- [x] Bump away algorithm, #167 
- [x] Elasticity affects ball-ball and ball-wall collisions.
- [x] How state is saved and implications for reset and step back buttons, #183 & #209
- [x] Link to https://github.com/phetsims/collision-lab/blob/master/doc/model.md
- [x] Recommend pausing the sim when setting up experiments. Frequent changes while in motion can lead to hard-to-interpret (though accurate) behavior, #176, #178
- [x] `supportsPanAndZoom` and `screens`
- [x] Stepping back only allowed in perfectly-elastic collisions. This is to avoid displaying alternate histories that arise from numerical imprecisions that get magnified significantly for every collision (and glancing collisions magnify it also). - #183 

Legacy tips: https://phet.colorado.edu/services/download-servlet?filename=/teachers-guide/collision-lab-guide.pdf

**Comment by arouinfar** [comment]
Teacher Tips have been completed, uploaded to SharePoint, and published to the website. Closing.
